### ISSUE TITLE
1 validation error for QualityDefinition

### ISSUE THREAD

**Issue by Dialgatrainer02** [buildarr/buildarr-sonarr#72]
hello when running buildarr specificly during the sonarr configuration no matter what i out in the quality.definitions is rejects as being  over 400 and therefore incorrect 
```
quality:
      trash_id: bef99584217af744e404ed44a33af589
      definitions:
        Bluray-480p: # "Quality" column name (not "Title")
          min: 2
          max: 100
```
this is taken stright from the wiki https://buildarr.github.io/plugins/sonarr/configuration/quality/ asnd it doesnt work 
```
2024-09-04 17:19:20,197 buildarr:1 buildarr.cli.daemon [ERROR] <sonarr> (default) An error occurred while applying initial configuration: 1 validation error for QualityDefinition
max
  ensure this value is less than or equal to 400 (type=value_error.number.not_le; limit_value=400)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/buildarr/cli/daemon.py", line 215, in _initial_run
    run_apply()
  File "/usr/local/lib/python3.11/site-packages/buildarr/cli/run.py", line 166, in _run
    render_instance_configs()
  File "/usr/local/lib/python3.11/site-packages/buildarr/config/render_instance_configs.py", line 54, in render_instance_configs
    instance_configs[plugin_name][instance_name] = manager.render(instance_config)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr/manager/__init__.py", line 105, in render
    return instance_config.render()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr_sonarr/config/__init__.py", line 312, in render
    copy._render()
  File "/usr/local/lib/python3.11/site-packages/buildarr_sonarr/config/__init__.py", line 320, in _render
    self.settings.quality._render()
  File "/usr/local/lib/python3.11/site-packages/buildarr_sonarr/config/quality.py", line 169, in _render
    self.definitions[definition_name] = QualityDefinition(
                                        ^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for QualityDefinition
max
  ensure this value is less than or equal to 400 (type=value_error.number.not_le; limit_value=400)
```

this error also appears if i completely remove the definitions key and only have trash id
```
    quality:
      trash_id: bef99584217af744e404ed44a33af589
```
still gives the same quality deefinition issue

**Comment by LifeDay** [comment]
I'm having the same issue.
@Dialgatrainer02  Did you ever find a resolution for this?

**Comment by Dialgatrainer02** [comment]
no i have kinda given up on buildarr for now im going to make my media server by hand in the short term until either it becomes permanent or this gets updated 

@Callum027 is buildarr abandoned?

**Comment by maplepy** [comment]
> [@Callum027](https://github.com/Callum027) is buildarr abandoned?

I think it is
